/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package battleship;


import battleship.controller.StartController;
import battleship.model.BattleshipGame;
import battleship.model.Game;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;

public class App extends Application {
  private Stage stage;

  /**
   * show the start view and set the look
   * @param currStage
   * @param xmlPath
   * @param gameEntity
   * @throws IOException
   */
  public void startView(Stage currStage, String xmlPath, BattleshipGame gameEntity) throws IOException {
    URL xmlResource = getClass().getResource(xmlPath);
    FXMLLoader loader = new FXMLLoader(xmlResource);
    loader.setControllerFactory((c) -> {
      return new StartController(currStage, gameEntity);
    });

    Scene scene = new Scene(loader.load(), 924, 600);
    currStage.setTitle("Battleship Game");
    currStage.setScene(scene);
    currStage.show();
  }



  /**
   * start to show the first view
   * @param primaryStage
   * @throws IOException
   */
  @Override
  public void start(Stage primaryStage) throws IOException {
    this.stage = primaryStage;
    Thread.setDefaultUncaughtExceptionHandler(new ErrorReporter());
    startView(this.stage, "/ui/startPage.fxml", null);
  }

  public static void main(String[] args) {
    launch();
  }

}
